config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'images#index'
    resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim_detail.rb
class ClaimDetail < ApplicationRecord
	has_many :images,as: :imageable,dependent: :destroy
	accepts_nested_attributes_for :images,:allow_destroy => true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :file, ImageUploader
    belongs_to :imageable, polymorphic: true,optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  # GET /images
  # GET /images.json
  def index
    @claims = ClaimDetail.all
  end
	

   # GET /images/new
  def new
    @claim =  ClaimDetail.new
    4.times do
      image = @claim.images.build
    end
  end
    
  
  # POST /images
  # POST /images.json
  def create
    @claim = ClaimDetail.new(claim_params)
    respond_to do |format|
    if @claim.save!   
        format.html { redirect_to root_path, flash[:success] = "Data saved." }
    else
     format.html { redirect_to root_path, flash[:error] = "Sorry!! Something went wrong." }
    end
   end
  end
	

  # GET /images/1
  # GET /images/1.json
  def show
    @claim = ClaimDetail.find_by(id: params[:id])
  end
     
  private
	# Never trust parameters from the scary internet, only allow the white list through.
  def claim_params
    params.require(:claim_detail).permit(:id,:title, :_destroy, images_attributes: [:id, :detail, :file , :_destroy] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_image_form.html.erb
<div class="captureImageBox" style="width: 268px;">
        <label><%#= a.text_field :detail , class: "form-control",placeholder: "Detail"%><!-- Detail of damage 2 --></label>
       <div class="captureImageBox1">
        <label>
       <%= image_tag ( a.object.present? && a.object.file_url.present? ? a.object.file_url : "/assets/img1.png") , id: "img_tag" , onclick: "set_img_tag_id(this)" , height: "193.11px" , width: "268px" %>
       <span style= "display: none;"  >
        <%= a.file_field :file , onchange: "readURL1(this)" %></span></label>
       </div>

 <%= a.link_to_remove "Remove" , class: "btn btn-danger" %>
</div>

app/views/images/index.html.erb
<div class="container" style="padding:20px 0">
<h1>All Claim Data</h1>
   <h2>
      <%= link_to "New" , new_image_path, class: "btn btn-primary" %>
   </h2>
   <div class="table-responsive">
      <table border=2 class="table table-bordered" >
         <th>Claim Title</th>
         <th>Action</th>
         <% @claims.each do |f| %>
         <tr>
            <td><i><%= f.title%></i></td>
            <td><%= link_to "Show" , image_path(f.id), class: "btn btn-primary" %> </td>
         </tr>
         <% end %>
      </table>
   </div>
</div>

app/views/images/new.html.erb
<%= nested_form_for @claim , url: images_path, methods: "post",local: true, class: "mb0" do |f| %>
<div class="globalBox">
   <div class="globalBoxHead">CLAIM PHOTO CAPTURE</div>
   <div class="globalBoxBody">
      <h3 class="text-center head3">REPLACE WITH ANY NICE PHOTO</h3>
      <p class="mb0">A fast and easy way to capture your claim photos and documents!</p>
   </div>
   <div class="backColorOverlay">
      <span style="width:70%;"></span>
   </div>
   <div class="globalBoxBody">
      <!-- <p class="mb10 lineHeight1">Claim No.: <span><%= @claim.id %></span></p> -->
      <p class="mb10 lineHeight1"><%= f.text_field :title , placeholder: "Please enter the claim title" , class: "form-control",required: true %></p>
      <h3 class="head4">Photo upload/capture</h3>
   </div>
   <div class="photoCaptureBox bgGray d-flex flex-wrap mb15">
      <!-- captureImageBox Start -->
      <%= f.fields_for :images do |nest_form| %>
      <%= (render 'image_form', a: nest_form )  %>
      <% end %>
      <!-- captureImageBox End --> 
      <!-- captureImageBox Start -->
      <%= f.link_to_add image_tag("/assets/attachbg.png", alt: "images" ), :images ,class: "change_img_tag_id", style: "margin-top: 30px" %>
      <!-- captureImageBox End --> 
   </div>
   <!-- Photo Capture Box End -->
   <div class="globalBoxBody">
      <label class="checkboxDesign d-flex align-items-center mb10 lineHeight1">
      <input type="checkbox" checked="checked"  required="true" >
      I agree to the <a href="javascript:void(0);">Terms & Conditions<a></a>
      </label>
   </div>
   <div class="text-center mb15">
      <%= f.submit "SEND",  class: "btn btnSubmit"%>
      <!-- <button type="submit" class="btn btnSubmit">SEND</button> -->
   </div>
</div>
<% end %>

<script type="text/javascript">
     var count = $("img[id^=img_tag]").length
   
   $(document).ready(function(){
     for(var i = 0; i < count; i++) {
     uid = get_uid();
       $('#img_tag').attr('id',$('#img_tag').attr('id')+uid);
     }
     $('.change_img_tag_id').on('click',function(){
     alert("grth")
       uid = get_uid();
       $('#img_tag').attr('id',$('#img_tag').attr('id')+uid);
     });
   });
</script>

app/views/images/show.html.erb
<div class="globalBox">
   <div class="globalBoxHead">CLAIM PHOTO CAPTURED</div>
   <div class="globalBoxBody">
      <h3 class="text-center head3">NICE PHOTOS</h3>
      <p class="mb0">A fast and easy way to capture your claim photos and documents!</p>
   </div>
   <div class="backColorOverlay">
      <span style="width:70%;"></span>
   </div>
   <div class="globalBoxBody">
      <p class="mb10 lineHeight1">Claim No: <span><%= @claim.id %></span></p>
      <p class="mb10 lineHeight1"><%= @claim.title %></p>
      <h3 class="head4">Photo uploaded/captured</h3>
   </div>
   <div class="photoCaptureBox bgGray d-flex flex-wrap mb15">
      <!-- captureImageBox Start -->
      <% @claim.images.each do |f| %>
      <div class="captureImageBox">
         <!-- <label>Image Detail:<span><%#= f.detail %></span></label> -->
         <div class="captureBox">
            <img src='<%= f.file_url.present? ? f.file_url : "/assets/img1.png" %>' alt="images" height= "193.11px"  width= "268px" />
            <!-- <input type="file"/> -->
         </div>
      </div>
      <% end %>
      <!-- captureImageBox End --> 
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MobiloitteTestProject</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= alertify_flash(wait: 5) %>
  </body>
</html>